version: 0.2
run-as: root
env:
  variables:
      ENV_NAME: "DEV"
phases:
  install:
    commands:
      - "apt update"
  pre_build:
    commands:
       - pip install -r requirements.txt
  build:
    commands:
       - pytest
       - ls -lart
  post_build:
    commands:
       - pytest --cov=core tests
artifacts:
  files:
     - "**/*"
  name: artifact
cache:
  paths:
     - "/root/.cache/pip"
